/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnersIndexRouteImport } from './routes/owners/index'
import { Route as DogsIndexRouteImport } from './routes/dogs/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as StaysNewRouteImport } from './routes/stays/new'
import { Route as StaysStayIdRouteImport } from './routes/stays/$stayId'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as OwnersNewRouteImport } from './routes/owners/new'
import { Route as OwnersOwnerIdRouteImport } from './routes/owners/$ownerId'
import { Route as DogsNewRouteImport } from './routes/dogs/new'
import { Route as DogsDogIdIndexRouteImport } from './routes/dogs/$dogId/index'
import { Route as DogsDogIdEditRouteImport } from './routes/dogs/$dogId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersIndexRoute = OwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsIndexRoute = DogsIndexRouteImport.update({
  id: '/dogs/',
  path: '/dogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysNewRoute = StaysNewRouteImport.update({
  id: '/stays/new',
  path: '/stays/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysStayIdRoute = StaysStayIdRouteImport.update({
  id: '/stays/$stayId',
  path: '/stays/$stayId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersNewRoute = OwnersNewRouteImport.update({
  id: '/owners/new',
  path: '/owners/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersOwnerIdRoute = OwnersOwnerIdRouteImport.update({
  id: '/owners/$ownerId',
  path: '/owners/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsNewRoute = DogsNewRouteImport.update({
  id: '/dogs/new',
  path: '/dogs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsDogIdIndexRoute = DogsDogIdIndexRouteImport.update({
  id: '/dogs/$dogId/',
  path: '/dogs/$dogId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsDogIdEditRoute = DogsDogIdEditRouteImport.update({
  id: '/dogs/$dogId/edit',
  path: '/dogs/$dogId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dogs/new': typeof DogsNewRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/share/$token': typeof ShareTokenRoute
  '/stays/$stayId': typeof StaysStayIdRoute
  '/stays/new': typeof StaysNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/dogs/': typeof DogsIndexRoute
  '/owners/': typeof OwnersIndexRoute
  '/dogs/$dogId/edit': typeof DogsDogIdEditRoute
  '/dogs/$dogId/': typeof DogsDogIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dogs/new': typeof DogsNewRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/share/$token': typeof ShareTokenRoute
  '/stays/$stayId': typeof StaysStayIdRoute
  '/stays/new': typeof StaysNewRoute
  '/calendar': typeof CalendarIndexRoute
  '/dogs': typeof DogsIndexRoute
  '/owners': typeof OwnersIndexRoute
  '/dogs/$dogId/edit': typeof DogsDogIdEditRoute
  '/dogs/$dogId': typeof DogsDogIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dogs/new': typeof DogsNewRoute
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRoute
  '/share/$token': typeof ShareTokenRoute
  '/stays/$stayId': typeof StaysStayIdRoute
  '/stays/new': typeof StaysNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/dogs/': typeof DogsIndexRoute
  '/owners/': typeof OwnersIndexRoute
  '/dogs/$dogId/edit': typeof DogsDogIdEditRoute
  '/dogs/$dogId/': typeof DogsDogIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dogs/new'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/share/$token'
    | '/stays/$stayId'
    | '/stays/new'
    | '/calendar/'
    | '/dogs/'
    | '/owners/'
    | '/dogs/$dogId/edit'
    | '/dogs/$dogId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dogs/new'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/share/$token'
    | '/stays/$stayId'
    | '/stays/new'
    | '/calendar'
    | '/dogs'
    | '/owners'
    | '/dogs/$dogId/edit'
    | '/dogs/$dogId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dogs/new'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/share/$token'
    | '/stays/$stayId'
    | '/stays/new'
    | '/calendar/'
    | '/dogs/'
    | '/owners/'
    | '/dogs/$dogId/edit'
    | '/dogs/$dogId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DogsNewRoute: typeof DogsNewRoute
  OwnersOwnerIdRoute: typeof OwnersOwnerIdRoute
  OwnersNewRoute: typeof OwnersNewRoute
  ShareTokenRoute: typeof ShareTokenRoute
  StaysStayIdRoute: typeof StaysStayIdRoute
  StaysNewRoute: typeof StaysNewRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DogsIndexRoute: typeof DogsIndexRoute
  OwnersIndexRoute: typeof OwnersIndexRoute
  DogsDogIdEditRoute: typeof DogsDogIdEditRoute
  DogsDogIdIndexRoute: typeof DogsDogIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/': {
      id: '/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof OwnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/': {
      id: '/dogs/'
      path: '/dogs'
      fullPath: '/dogs/'
      preLoaderRoute: typeof DogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/new': {
      id: '/stays/new'
      path: '/stays/new'
      fullPath: '/stays/new'
      preLoaderRoute: typeof StaysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$stayId': {
      id: '/stays/$stayId'
      path: '/stays/$stayId'
      fullPath: '/stays/$stayId'
      preLoaderRoute: typeof StaysStayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/new': {
      id: '/owners/new'
      path: '/owners/new'
      fullPath: '/owners/new'
      preLoaderRoute: typeof OwnersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/$ownerId': {
      id: '/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/owners/$ownerId'
      preLoaderRoute: typeof OwnersOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/new': {
      id: '/dogs/new'
      path: '/dogs/new'
      fullPath: '/dogs/new'
      preLoaderRoute: typeof DogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/$dogId/': {
      id: '/dogs/$dogId/'
      path: '/dogs/$dogId'
      fullPath: '/dogs/$dogId/'
      preLoaderRoute: typeof DogsDogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/$dogId/edit': {
      id: '/dogs/$dogId/edit'
      path: '/dogs/$dogId/edit'
      fullPath: '/dogs/$dogId/edit'
      preLoaderRoute: typeof DogsDogIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DogsNewRoute: DogsNewRoute,
  OwnersOwnerIdRoute: OwnersOwnerIdRoute,
  OwnersNewRoute: OwnersNewRoute,
  ShareTokenRoute: ShareTokenRoute,
  StaysStayIdRoute: StaysStayIdRoute,
  StaysNewRoute: StaysNewRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DogsIndexRoute: DogsIndexRoute,
  OwnersIndexRoute: OwnersIndexRoute,
  DogsDogIdEditRoute: DogsDogIdEditRoute,
  DogsDogIdIndexRoute: DogsDogIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
